config/routes.rb
Rails.application.routes.draw do

  get 'pages/index'

  root to: "pages#index"

  get '/profil', to: 'users#edit', as: :profil
  patch '/profil', to: 'users#update'

  get '/animaux/:slug', to: 'posts#species', as: :species_posts

  # sessions

  get '/login', to: 'sessions#new', as: :new_session
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :destroy_session

  resources :pets do
    resource :subscriptions, only: [:create, :destroy]
  end
  resources :posts do
    collection do
      get 'me'
    end
  end
  resources :passwords, only: [:new, :create, :edit, :update]
  # resources :sessions, only: [:new, :create]
  resources :users, only: [:new, :create] do
    member do
      get 'confirm'
    end
  end

end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  belongs_to :species, counter_cache: true
  has_and_belongs_to_many :posts
  has_many :subscriptions
  has_many :subscribers, through: :subscriptions, source: :user

  validates :name, :gender, :birthday, presence: true
  validates :gender, format: {with: /\A(M|F)\z/}
  validates :avatar_file, presence: true, on: :create
  validate :birthday_not_future

  has_image :avatar
  after_destroy :destroy_posts

  def age
    Time.now.year - birthday.year
  end

  def birthday_not_future
    if birthday.present? && birthday.future?
      errors.add(:birthday, "ne peut être dans le futur")
    end
  end

  def followedBy?(user)
    subscriptions.where(user_id: user.id).count > 0 if user.respond_to? :id
  end

  private
  def destroy_posts

    Post.find_by_sql('SELECT * FROM posts LEFT JOIN pets_posts ON pets_posts.post_id = Post.id WHERE pets_posts.post_id IS NULL').each do |post|
      post.destroy
    end
  end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  before_action :set_pet, only: [:edit, :update, :destroy]
  skip_before_action :only_signed_in, only: [:show]

  def show
    @pet = Pet.find(params[:id])
  end

  def index
    @pets = current_user.pets
  end

  def new
    @pet = current_user.pets.new
  end

  def create
    @pet = current_user.pets.new(pet_params)
    if @pet.save
      redirect_to pets_path, success: 'Votre animal a bien été créé'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @pet.update(pet_params)
      redirect_to pets_path, success:'Votre animal a bien été modifié'
    else
      render :edit
    end
  end

  def destroy
    @pet.destroy
    redirect_to pets_path, success:'Votre animal a bien été supprimé'
  end

  private
  def pet_params
    params.require(:pet).permit(:name, :gender, :birthday, :species_id, :avatar_file)
  end

  def set_pet
    @pet = current_user.pets.find(params[:id])
  end

end

app/views/pets/_form.html.erb
<%= form_for pet, html:{class:'form-horizontal'} do |f| %>

<% if pet.errors.any? %>
  <div class="alert alert-danger">
      <ul>
        <% pet.errors.full_messages.each do |message| %>
        <li><%=message %></li>
        <% end %>
      </ul>
  </div>
<% end %>

    <div class="form-group">
      <%= f.label :name, "Nom", class:'col-md-4 control-label' %>
      <div class="col-md-6">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :avatar_file, "Avatar", class:'col-md-4 control-label' %>
      <div class="col-md-6">
        <%= f.file_field :avatar_file, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :species_id, "Espèce", class:'col-md-4 control-label' %>
      <div class="col-md-6">
        <%= f.select :species_id, Species.pluck(:name, :id), {}, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :gender, "Sexe", class:'col-md-4 control-label' %>
      <div class="col-md-6">
        <%= f.select :gender, {Male: :M, Femelle: :F}, {}, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :birthday, "Date de naissance", class:'col-md-4 control-label' %>
      <div class="col-md-6">
        <%= f.text_field :birthday, class: 'form-control form-datepicker' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-4 col-md-6">
        <button type="submit" class="btn btn-primary"><%= pet.new_record? ? 'Créer' : 'Modifier' %> </button>
      </div>
    </div>


<% end %>

app/views/pets/_pet.html.erb
<li class="list-group-item">
  <%= link_to pet do %>
    <h4 class="list-group-item-heading"><%= pet.name %></h4>
    <p class="list-group-item-text"><%= pet.age.to_s + ' ' + 'an'.pluralize(pet.age) %></p>
    <% end %>
</li>

app/views/pets/edit.html.erb
<% content_for :content do %>

<div class="panel panel-default">
  <div class="panel-heading">Modifier <%= @pet.name %> </div>
  <div class="panel-body">
    <%= render 'form', pet: @pet %>
  </div>
</div>

<% end %>

<%= render template: 'layouts/profile' %>

app/views/pets/index.html.erb
<% content_for :tab, :pets %>
<% content_for :content do %>

<h1>Gérer mes animaux</h1>

<p class="text-right">
  <a href="<%= new_pet_path %>" class="btn btn-primary">Ajouter un animal</a>
</p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Avatar</th>
      <th>Nom</th>
      <th>Sexe</th>
      <th>Age</th>
      <th>Espèce</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
      <% @pets.each do |pet| %>
        <tr>
          <td><%= image_tag pet.avatar_url%></td>
          <td><%= pet.name %></td>
          <td><%= pet.gender %></td>
          <td><%= pet.age %> <%= 'an'.pluralize(pet.age) %></td>
          <td><%= pet.species.name %> </td>
          <td>
              <%= link_to 'Voir', pet, class:'btn btn-default' %>
              <%= link_to 'Editer', [:edit, pet], class:'btn btn-primary' %>
              <%= link_to 'Supprimer', pet, class:'btn btn-danger', data: {method: :delete, confirm: 'Voulez-vous vraiment supprimer cet animal?'} %>
          </td>
        </tr>
      <% end %>
  </tbody>
</table>

<% end %>

<%= render template: 'layouts/profile' %>

app/views/pets/new.html.erb
<% content_for :content do %>

<div class="panel panel-default">
  <div class="panel-heading">Créer un nouvel animal</div>
  <div class="panel-body">
    <%= render 'form', pet: @pet %>
  </div>
</div>

<% end %>

<%= render template: 'layouts/profile' %>

app/views/pets/show.html.erb
<div class="row">
  <div class="col-md-2">
    <%= image_tag @pet.avatar_url, class: 'img-circle' %>
  </div>
  <div class="col-md-10">
    <h2><%= @pet.name %></h2>
    <% if user_signed_in? %>
      <% if @pet.followedBy?(current_user) %>
        <%=link_to "Se désabonner", [@pet, Subscription], method: :delete, class:'btn btn-warning' %>
      <% else %>
        <%=link_to "S'abonner", [@pet, Subscription], method: :post, class:'btn btn-success' %>
      <% end %>
    <% end %>
  </div>
</div>

<div class="row">
  <% @pet.posts.each do |post| %>
  <div class="col-md-4">
    <%= render post %>
  </div>
  <% end %>
</div>