config/routes.rb
Rails.application.routes.draw do

  get 'pages/index'

  root to: "pages#index"

  get '/profil', to: 'users#edit', as: :profil
  patch '/profil', to: 'users#update'

  get '/animaux/:slug', to: 'posts#species', as: :species_posts

  # sessions

  get '/login', to: 'sessions#new', as: :new_session
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :destroy_session

  resources :pets do
    resource :subscriptions, only: [:create, :destroy]
  end
  resources :posts do
    collection do
      get 'me'
    end
  end
  resources :passwords, only: [:new, :create, :edit, :update]
  # resources :sessions, only: [:new, :create]
  resources :users, only: [:new, :create] do
    member do
      get 'confirm'
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Petsy</title>
    <%= csrf_meta_tags %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- select2 CDN-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js"></script>

  </head>

  <body>

    <div class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <a href="<%= root_path %>" class="navbar-brand">Petsy</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <%= current_user.username %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li> <%=link_to 'Mon profil', profil_path %> </li>
              <li> <%=link_to 'Se déconnecter', destroy_session_path, data: {method: :delete} %> </li>
            </ul>
          </li>


          <%else %>
            <li><a href="<%= new_user_path%>">S'inscrire</a></li>
            <li><a href="<%= new_session_path %>">Se connecter</a></li>
          <% end %>

        </ul>
      </div>
    </div>

    <div class="container">

      <% if flash[:success] %>
        <div class="alert alert-success">
            <%= flash[:success] %>
        </div>
      <% end %>

      <% if flash[:danger] %>
        <div class="alert alert-danger">
            <%= flash[:danger] %>
        </div>
      <% end %>

      <%= yield %>

    </div>
  </body>

  <%= javascript_include_tag 'application','data-turbolinks-eval': 'false', 'data-turbolinks-track': 'reload' %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</html>

app/views/layouts/profile.html.erb
<div class="row">
  <div class="col-md-8">
    <%= yield(:content) %>
  </div>
  <div class="col-md-4">
    <div class="list-group">
      <a href="<%= posts_path %>" class="list-group-item <%= yield(:tab) == 'posts' ? 'active' : '' %> ">Mes animaux préférés</a>
      <a href="<%= me_posts_path %>" class="list-group-item <%= yield(:tab) == 'me' ? 'active' : '' %> ">Mes photos</a>
      <a href="<%= profil_path %>" class="list-group-item <%= yield(:tab) == 'profil' ? 'active' : '' %> ">Mon compte</a>
      <a href="<%= pets_path %>" class="list-group-item <%= yield(:tab) == 'pets' ? 'active' : '' %>">Mes animaux</a>
    </div>
  </div>
</div>